/**
 * predictionController.js
 * =======================
 * Controller for the ML Placement Readiness Prediction endpoint.
 *
 * Route: POST /api/prediction/predict
 *
 * Flow:
 *   1. Authenticate via existing `protect` middleware (JWT).
 *   2. Validate all 9 input features.
 *   3. Pass features to mlPredictionService.runPrediction().
 *   4. Return { success, score, label } or a clean error response.
 *
 * ACADEMIC DISCLAIMER:
 *   The ML model is trained on SYNTHETIC data.
 *   Predictions must NOT be used for real-world placement decisions.
 */

const { runPrediction } = require('../services/mlPredictionService');

/**
 * @desc    Run ML placement readiness prediction
 * @route   POST /api/prediction/predict
 * @access  Private (requires JWT via `protect` middleware)
 */
const predictPlacementReadiness = async (req, res, next) => {
  try {
    const {
      cgpa,
      backlogs,
      coding,
      sql,
      aptitude,
      communication,
      projects,
      certifications,
      internships,
    } = req.body;

    // ── Input validation ────────────────────────────────────────────────────
    const errors = [];

    const cgpaVal          = Number(cgpa);
    const backlogsVal      = Number(backlogs);
    const codingVal        = Number(coding);
    const sqlVal           = Number(sql);
    const aptitudeVal      = Number(aptitude);
    const communicationVal = Number(communication);
    const projectsVal      = Number(projects);
    const certificationsVal = Number(certifications);
    const internshipsVal   = Number(internships);

    if (cgpa === undefined || cgpa === '' || isNaN(cgpaVal) || cgpaVal < 0 || cgpaVal > 10) {
      errors.push('cgpa must be a number between 0 and 10');
    }
    if (backlogs === undefined || backlogs === '' || isNaN(backlogsVal) || backlogsVal < 0) {
      errors.push('backlogs must be a non-negative number');
    }
    if (coding === undefined || coding === '' || isNaN(codingVal) || codingVal < 0 || codingVal > 100) {
      errors.push('coding must be a number between 0 and 100');
    }
    if (sql === undefined || sql === '' || isNaN(sqlVal) || sqlVal < 0 || sqlVal > 100) {
      errors.push('sql must be a number between 0 and 100');
    }
    if (aptitude === undefined || aptitude === '' || isNaN(aptitudeVal) || aptitudeVal < 0 || aptitudeVal > 100) {
      errors.push('aptitude must be a number between 0 and 100');
    }
    if (communication === undefined || communication === '' || isNaN(communicationVal) || communicationVal < 0 || communicationVal > 100) {
      errors.push('communication must be a number between 0 and 100');
    }
    if (projects === undefined || projects === '' || isNaN(projectsVal) || projectsVal < 0) {
      errors.push('projects must be a non-negative number');
    }
    if (certifications === undefined || certifications === '' || isNaN(certificationsVal) || certificationsVal < 0) {
      errors.push('certifications must be a non-negative number');
    }
    if (internships === undefined || internships === '' || isNaN(internshipsVal) || internshipsVal < 0) {
      errors.push('internships must be a non-negative number');
    }

    if (errors.length > 0) {
      return res.status(400).json({
        success: false,
        message: 'Validation failed',
        errors,
      });
    }

    // ── Build feature object for the ML bridge ─────────────────────────────
    const features = {
      cgpa:           cgpaVal,
      backlogs:       backlogsVal,
      coding:         codingVal,
      sql:            sqlVal,
      aptitude:       aptitudeVal,
      communication:  communicationVal,
      projects:       projectsVal,
      certifications: certificationsVal,
      internships:    internshipsVal,
    };

    // ── Call the ML prediction service ─────────────────────────────────────
    const prediction = await runPrediction(features);

    // ── Return result ───────────────────────────────────────────────────────
    return res.status(200).json({
      success: true,
      score:   prediction.score,
      label:   prediction.label,
      // Academic disclaimer — always surfaced with the prediction
      disclaimer:
        'This prediction is generated by a Decision Tree Regressor ' +
        'trained on SYNTHETIC data. It is an academic prototype and ' +
        'must NOT be used for real-world placement decisions.',
    });
  } catch (error) {
    // Log the full error server-side but return a clean message to the client
    console.error('[Prediction Controller] ML prediction error:', error.message);
    return res.status(503).json({
      success: false,
      message:
        'The ML prediction service is temporarily unavailable. ' +
        'Please ensure the Python environment is set up and the model is trained.',
    });
  }
};

module.exports = { predictPlacementReadiness };
